# -*- coding: utf-8 -*-
"""Evidencia APPL 30 min

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_uSxFa3XkX33RpnfWBcFu2_CIotWwOP
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, coint
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.statespace.sarimax import SARIMAX
from google.colab import files

# Step 1: Upload Excel file for a single company
print("Upload stock data Excel file (e.g., AAPL.xlsx)")
uploaded = files.upload()
stock_file = list(uploaded.keys())[0]
stock_data = pd.read_excel(stock_file)

# Step 2: Extract Closing price column and set Date index
if 'Date' in stock_data.columns:
    stock_data['Date'] = pd.to_datetime(stock_data['Date'])
    stock_data = stock_data.set_index('Date')
    stock_close = stock_data['Close'].dropna()
else:
    # If no Date column, create a sequential date index
    print("Warning: No Date column found, creating sequential date index")
    stock_close = stock_data['Close'].dropna()
    stock_close.index = pd.date_range(start='2020-01-01', periods=len(stock_close), freq='D')

print(f"Length of stock closing prices: {len(stock_close)}")

# Step 3: Random Walk Simulation
np.random.seed(42)
random_walk = np.cumsum(np.random.normal(0, 1, len(stock_close)))
random_walk = random_walk + stock_close.iloc[0]  # Start at same initial price
random_walk_series = pd.Series(random_walk, index=stock_close.index)

# Step 4: Perform Augmented Dickey-Fuller (ADF) Unit Root Test
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f'\nADF Unit Root Test for {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print(f'Critical Values: {result[4]}')
    if result[1] < 0.05:
        print(f'{name} is stationary (reject null hypothesis of unit root)')
    else:
        print(f'{name} is non-stationary (fail to reject null hypothesis of unit root)')
    return result[1]

# Run ADF test on original series, random walk, and differenced series
adf_test(stock_close, 'Stock Closing Prices')
adf_test(random_walk_series, 'Random Walk Simulation')
stock_diff = stock_close.diff().dropna()
adf_test(stock_diff, 'Differenced Stock Closing Prices')

# Step 5: Perform Cointegration Test
print("\nCointegration Test between Stock Closing Prices and Random Walk:")
try:
    score, p_value, _ = coint(stock_close, random_walk_series)
    print(f'Cointegration Test Statistic: {score:.4f}')
    print(f'p-value: {p_value:.4f}')
    if p_value < 0.05:
        print("Stock and Random Walk are cointegrated (reject null hypothesis)")
    else:
        print("Stock and Random Walk are not cointegrated (fail to reject null hypothesis)")
except ValueError as e:
    print(f"Error in cointegration test: {e}")

# Step 6: Fit AR Model
def fit_ar_model(series, name, lags=1):
    model = AutoReg(series, lags=lags)
    results = model.fit()
    print(f'\nAR({lags}) Model Summary for {name}:')
    print(results.summary())
    return results

# Step 7: Fit ARMA Model
def fit_arma_model(series, name, order=(1,0,1)):
    model = SARIMAX(series, order=order)
    results = model.fit(disp=False)
    print(f'\nARMA Model Summary for {name}:')
    print(results.summary())
    return results

# Step 8: Fit ARIMA Model
def fit_arima_model(series, name, order=(1,1,1)):
    model = ARIMA(series, order=order)
    results = model.fit()
    print(f'\nARIMA Model Summary for {name}:')
    print(results.summary())
    return results

# Fit models
ar_model = fit_ar_model(stock_close, 'Stock Closing Prices', lags=1)
arma_model = fit_arma_model(stock_close, 'Stock Closing Prices', order=(1,0,1))
arima_model = fit_arima_model(stock_close, 'Stock Closing Prices', order=(1,1,1))

# Step 9: Forecasting with ARIMA
forecast_steps = 10
forecast = arima_model.forecast(steps=forecast_steps)

# Ensure index is datetime
if not isinstance(stock_close.index, pd.DatetimeIndex):
    stock_close.index = pd.date_range(start='2020-01-01', periods=len(stock_close), freq='D')

# Create forecast index
try:
    forecast_index = pd.date_range(start=stock_close.index[-1] + pd.Timedelta(days=1), periods=forecast_steps, freq='D')
except TypeError:
    # Fallback for non-datetime index
    last_date = pd.to_datetime('2020-01-01') + pd.Timedelta(days=len(stock_close)-1)
    forecast_index = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=forecast_steps, freq='D')

forecast_series = pd.Series(forecast, index=forecast_index)

# Get confidence intervals
forecast_obj = arima_model.get_forecast(steps=forecast_steps)
conf_int = forecast_obj.conf_int(alpha=0.05)
conf_int.index = forecast_index

# Plot forecast
plt.figure(figsize=(10,6))
plt.plot(stock_close[-30:], label='Historical Stock Close')
plt.plot(forecast_series, label='Forecast', linestyle='--')
plt.fill_between(forecast_index, conf_int.iloc[:,0], conf_int.iloc[:,1], color='gray', alpha=0.2, label='95% Confidence Interval')
plt.title('ARIMA Forecast for Stock Closing Prices')
plt.legend()
plt.show()

# Step 10: Decision-Making
last_price = stock_close[-1]
forecast_mean = forecast_series.mean()
print("\nDecision-Making Insights:")
print(f"Last observed price: ${last_price:.2f}")
print(f"Mean forecast price (next {forecast_steps} days): ${forecast_mean:.2f}")
if forecast_mean > last_price * 1.05:
    print("Recommendation: Consider BUYING (forecast indicates potential price increase)")
elif forecast_mean < last_price * 0.95:
    print("Recommendation: Consider SELLING (forecast indicates potential price decrease)")
else:
    print("Recommendation: HOLD (forecast indicates stable price movement)")

# Plot residuals for ARIMA
plt.figure(figsize=(10,4))
plt.plot(arima_model.resid)
plt.title('ARIMA Residuals for Stock')
plt.tight_layout()
plt.show()

# Plot Closing Prices and Random Walk
plt.figure(figsize=(10,6))
plt.plot(stock_close, label='Stock Close')
plt.plot(random_walk_series, label='Random Walk', linestyle='--')
plt.title('Stock Closing Prices vs Random Walk')
plt.legend()
plt.show()